# import vhr_human_resource
import vhr_human_resource_abstract
# ===Contract===
import vhr_mission_collaborator_contract
import vhr_result_collaborator_contract
import hr_contract_type_group
import hr_contract_type
import hr_contract_sub_type
import vhr_appendix_contract_type
import vhr_appendix_contract
import hr_contract
import vhr_bank_contract
import vhr_salary_contract


import vhr_mass_movement_mail_template_process
import vhr_working_record_mail_template_process
import vhr_termination_request_mail_template_process

# ===Termination Request===
import vhr_termination_request_permission
import vhr_termination_request
import vhr_resignation_type
import vhr_resignation_reason_group
import vhr_resignation_reason
import vhr_resign_reason_detail

# ===Working Records===
import vhr_sm_email
import vhr_working_record
# import vhr_working_record_permission
import vhr_working_record_hr_admin_permission
import vhr_mass_movement

import vhr_employee_instance
import hr_employee
import hr_department
import vhr_exit_checklist_request
import vhr_exit_checklist_detail

import vhr_multi_renew_contract_mail_template_process
import vhr_multi_renew_contract
import vhr_multi_renew_contract_detail

import vhr_dimension

import vhr_family_deduct
import ir_view_security
import ir_ui_view
import ir_attachment

import vhr_employee_assessment_result
import vhr_state_change

import vhr_permission_location

import vhr_log_error_system
import vhr_termination_agreement_contract
import vhr_resignation_link_exit_survey
import res_partner_bank

import vhr_department_history
import vhr_exit_checklist_department_fa

import vhr_hr_test_result
import vhr_multi_renew_contract_setting
import vhr_duty_free
import vhr_personal_document
